using Aurora.Devices.Layout.Layouts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aurora.Devices.Drevo
{
    public static class DrevoLayoutMap
    {
        public static readonly Dictionary<KeyboardKeys, int[]> BMKeyboard = new Dictionary<KeyboardKeys, int[]>
        {
            {KeyboardKeys.ESC, new int [] {0,0} },
            {KeyboardKeys.F1, new int [] {0, 1} },
            {KeyboardKeys.F2, new int [] {0, 2} },
            {KeyboardKeys.F3, new int [] {0, 3} },
            {KeyboardKeys.F4, new int [] {0, 4} },
            {KeyboardKeys.F5, new int [] {0, 6} },
            {KeyboardKeys.F6, new int [] {0, 7} },
            {KeyboardKeys.F7, new int [] {0, 8} },
            {KeyboardKeys.F8, new int [] {0, 9} },
            {KeyboardKeys.F9, new int [] {0, 11} },
            {KeyboardKeys.F10, new int [] {0, 12} },
            {KeyboardKeys.F11, new int [] {0, 13} },
            {KeyboardKeys.F12, new int [] {0, 14} },
            {KeyboardKeys.PRINT_SCREEN, new int [] {0, 15} },
            {KeyboardKeys.SCROLL_LOCK, new int [] {0, 16} },
            {KeyboardKeys.PAUSE_BREAK, new int [] {0, 17} },
            {KeyboardKeys.TILDE, new int [] {1, 0} },
            {KeyboardKeys.ONE, new int [] {1, 1} },
            {KeyboardKeys.TWO, new int [] {1, 2} },
            {KeyboardKeys.THREE, new int [] {1, 3} },
            {KeyboardKeys.FOUR, new int [] {1, 4} },
            {KeyboardKeys.FIVE, new int [] {1, 5} },
            {KeyboardKeys.SIX, new int [] {1, 6} },
            {KeyboardKeys.SEVEN, new int [] {1, 7} },
            {KeyboardKeys.EIGHT, new int [] {1, 8} },
            {KeyboardKeys.NINE, new int [] {1, 9} },
            {KeyboardKeys.ZERO, new int [] {1, 10} },
            {KeyboardKeys.MINUS, new int [] {1, 11} },
            {KeyboardKeys.EQUALS, new int [] {1, 12} },
            {KeyboardKeys.BACKSPACE, new int [] {1, 14} },
            {KeyboardKeys.INSERT, new int [] {1, 15} },
            {KeyboardKeys.HOME, new int [] {1, 16} },
            {KeyboardKeys.TAB, new int [] {2, 0} },
            {KeyboardKeys.Q, new int [] {2, 1} },
            {KeyboardKeys.W, new int [] {2, 2} },
            {KeyboardKeys.E, new int [] {2, 3} },
            {KeyboardKeys.R, new int [] {2, 4} },
            {KeyboardKeys.T, new int [] {2, 5} },
            {KeyboardKeys.Y, new int [] {2, 6} },
            {KeyboardKeys.U, new int [] {2, 7} },
            {KeyboardKeys.I, new int [] {2, 8} },
            {KeyboardKeys.O, new int [] {2, 9} },
            {KeyboardKeys.P, new int [] {2, 10} },
            {KeyboardKeys.OPEN_BRACKET, new int [] {2, 11} },
            {KeyboardKeys.CLOSE_BRACKET, new int [] {2,12} },
            {KeyboardKeys.BACKSLASH, new int [] {2, 14} },
            {KeyboardKeys.DELETE, new int [] {2, 15} },
            {KeyboardKeys.END, new int [] {2, 16} },
            {KeyboardKeys.PAGE_DOWN, new int [] {2, 17} },
            {KeyboardKeys.A, new int [] {3, 1} },
            {KeyboardKeys.S, new int [] {3, 2} },
            {KeyboardKeys.D, new int [] {3, 3} },
            {KeyboardKeys.F, new int [] {3, 4} },
            {KeyboardKeys.G, new int [] {3, 5} },
            {KeyboardKeys.H, new int [] {3, 6} },
            {KeyboardKeys.J, new int [] {3, 7} },
            {KeyboardKeys.K, new int [] {3, 8} },
            {KeyboardKeys.L, new int [] {3, 9} },
            {KeyboardKeys.SEMICOLON, new int [] {3, 10} },
            {KeyboardKeys.APOSTROPHE, new int [] {3, 11} },
            {KeyboardKeys.HASH, new int [] {3, 13} },
            {KeyboardKeys.ENTER, new int [] {3, 14} },
            {KeyboardKeys.LEFT_SHIFT, new int [] {4, 0} },
            {KeyboardKeys.BACKSLASH_UK, new int [] {4, 1} },
            {KeyboardKeys.Z, new int [] {4, 2} },
            {KeyboardKeys.X, new int [] {4, 3} },
            {KeyboardKeys.C, new int [] {4, 4} },
            {KeyboardKeys.V, new int [] {4, 5} },
            {KeyboardKeys.B, new int [] {4, 6} },
            {KeyboardKeys.N, new int [] {4, 7} },
            {KeyboardKeys.M, new int [] {4, 8} },
            {KeyboardKeys.COMMA, new int [] {4, 9} },
            {KeyboardKeys.PERIOD, new int [] {4, 10} },
            {KeyboardKeys.FORWARD_SLASH, new int [] {4, 11} },
            {KeyboardKeys.RIGHT_SHIFT, new int [] {4, 14} },
            {KeyboardKeys.ARROW_UP, new int [] {4, 16} },
            {KeyboardKeys.LEFT_CONTROL, new int [] {5, 0} },
            {KeyboardKeys.LEFT_WINDOWS, new int [] {5, 1} },
            {KeyboardKeys.LEFT_ALT, new int [] {5, 2} },
            {KeyboardKeys.SPACE, new int [] {5, 6} },
            {KeyboardKeys.RIGHT_ALT, new int [] {5, 10} },
            {KeyboardKeys.APPLICATION_SELECT, new int [] {5, 12} },
            {KeyboardKeys.FN_Key, new int [] {5, 11} },
            {KeyboardKeys.RIGHT_CONTROL, new int [] {5, 14} },
            {KeyboardKeys.ARROW_LEFT, new int [] {5, 15} },
            {KeyboardKeys.ARROW_DOWN, new int [] {5, 16} },
            {KeyboardKeys.ARROW_RIGHT, new int [] {5, 17} },
        };
    }
}