blank_issues_enabled: false
contact_links:
  - name: Discord
    url:  https://discord.gg/YAuBmg9
    about: Please direct any questions to our Discord server. You may also ask about any issue here - you may receive a faster response on Discord than GitHub.
    
