using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aurora.Devices.Omen
{
    class OmenKeys
    {
        private static int KEYBOARD_KEY_ESC = 1;
        private static int KEYBOARD_KEY_F1 = 2;
        private static int KEYBOARD_KEY_F2 = 3;
        private static int KEYBOARD_KEY_F3 = 4;
        private static int KEYBOARD_KEY_F4 = 5;
        private static int KEYBOARD_KEY_F5 = 6;
        private static int KEYBOARD_KEY_F6 = 7;
        private static int KEYBOARD_KEY_F7 = 8;
        private static int KEYBOARD_KEY_F8 = 9;
        private static int KEYBOARD_KEY_F9 = 10;
        private static int KEYBOARD_KEY_F10 = 11;
        private static int KEYBOARD_KEY_F11 = 12;
        private static int KEYBOARD_KEY_F12 = 13;
        private static int KEYBOARD_KEY_PRINT_SCREEN = 14;
        private static int KEYBOARD_KEY_SCROLL_LOCK = 15;
        private static int KEYBOARD_KEY_PAUSE_BREAK = 16;
        private static int KEYBOARD_KEY_JPN_HALFFULLWIDTH = 152;
        private static int KEYBOARD_KEY_OEM5 = 156;
        private static int KEYBOARD_KEY_TILDE = 17;
        private static int KEYBOARD_KEY_ONE = 18;
        private static int KEYBOARD_KEY_TWO = 19;
        private static int KEYBOARD_KEY_THREE = 20;
        private static int KEYBOARD_KEY_FOUR = 21;
        private static int KEYBOARD_KEY_FIVE = 22;
        private static int KEYBOARD_KEY_SIX = 23;
        private static int KEYBOARD_KEY_SEVEN = 24;
        private static int KEYBOARD_KEY_EIGHT = 25;
        private static int KEYBOARD_KEY_NINE = 26;
        private static int KEYBOARD_KEY_ZERO = 27;
        private static int KEYBOARD_KEY_MINUS = 28;
        private static int KEYBOARD_KEY_EQUALS = 29;
        private static int KEYBOARD_KEY_OEM6 = 169;
        private static int KEYBOARD_KEY_BACKSPACE = 30;
        private static int KEYBOARD_KEY_INSERT = 31;
        private static int KEYBOARD_KEY_HOME = 32;
        private static int KEYBOARD_KEY_PAGE_UP = 33;
        private static int KEYBOARD_KEY_NUM_LOCK = 34;
        private static int KEYBOARD_KEY_NUM_SLASH = 35;
        private static int KEYBOARD_KEY_NUM_ASTERISK = 36;
        private static int KEYBOARD_KEY_NUM_MINUS = 37;
        private static int KEYBOARD_KEY_TAB = 38;
        private static int KEYBOARD_KEY_Q = 39;
        private static int KEYBOARD_KEY_W = 40;
        private static int KEYBOARD_KEY_E = 41;
        private static int KEYBOARD_KEY_R = 42;
        private static int KEYBOARD_KEY_T = 43;
        private static int KEYBOARD_KEY_Y = 44;
        private static int KEYBOARD_KEY_U = 45;
        private static int KEYBOARD_KEY_I = 46;
        private static int KEYBOARD_KEY_O = 47;
        private static int KEYBOARD_KEY_P = 48;
        private static int KEYBOARD_KEY_OEM1 = 170;
        private static int KEYBOARD_KEY_OPEN_BRACKET = 49;
        private static int KEYBOARD_KEY_OEMPlus = 171;
        private static int KEYBOARD_KEY_CLOSE_BRACKET = 50;
        private static int KEYBOARD_KEY_BACKSLASH = 51;
        private static int KEYBOARD_KEY_DELETE = 52;
        private static int KEYBOARD_KEY_END = 53;
        private static int KEYBOARD_KEY_PAGE_DOWN = 54;
        private static int KEYBOARD_KEY_NUM_SEVEN = 55;
        private static int KEYBOARD_KEY_NUM_EIGHT = 56;
        private static int KEYBOARD_KEY_NUM_NINE = 57;
        private static int KEYBOARD_KEY_NUM_PLUS = 58;
        private static int KEYBOARD_KEY_CAPS_LOCK = 59;
        private static int KEYBOARD_KEY_A = 60;
        private static int KEYBOARD_KEY_S = 61;
        private static int KEYBOARD_KEY_D = 62;
        private static int KEYBOARD_KEY_F = 63;
        private static int KEYBOARD_KEY_G = 64;
        private static int KEYBOARD_KEY_H = 65;
        private static int KEYBOARD_KEY_J = 66;
        private static int KEYBOARD_KEY_K = 67;
        private static int KEYBOARD_KEY_L = 68;
        private static int KEYBOARD_KEY_OEMTilde = 157;
        private static int KEYBOARD_KEY_SEMICOLON = 69;
        private static int KEYBOARD_KEY_APOSTROPHE = 70;
        private static int KEYBOARD_KEY_HASHTAG = 71;
        private static int KEYBOARD_KEY_ENTER = 72;
        private static int KEYBOARD_KEY_NUM_FOUR = 73;
        private static int KEYBOARD_KEY_NUM_FIVE = 74;
        private static int KEYBOARD_KEY_NUM_SIX = 75;
        private static int KEYBOARD_KEY_LEFT_SHIFT = 76;
        private static int KEYBOARD_KEY_BACKSLASH_UK = 77;
        private static int KEYBOARD_KEY_Z = 78;
        private static int KEYBOARD_KEY_X = 79;
        private static int KEYBOARD_KEY_C = 80;
        private static int KEYBOARD_KEY_V = 81;
        private static int KEYBOARD_KEY_B = 82;
        private static int KEYBOARD_KEY_N = 83;
        private static int KEYBOARD_KEY_M = 84;
        private static int KEYBOARD_KEY_COMMA = 85;
        private static int KEYBOARD_KEY_PERIOD = 86;
        private static int KEYBOARD_KEY_FORWARD_SLASH = 87;
        private static int KEYBOARD_KEY_OEM8 = 158;
        private static int KEYBOARD_KEY_OEM102 = 159;
        private static int KEYBOARD_KEY_RIGHT_SHIFT = 88;
        private static int KEYBOARD_KEY_ARROW_UP = 89;
        private static int KEYBOARD_KEY_NUM_ONE = 90;
        private static int KEYBOARD_KEY_NUM_TWO = 91;
        private static int KEYBOARD_KEY_NUM_THREE = 92;
        private static int KEYBOARD_KEY_NUM_ENTER = 93;
        private static int KEYBOARD_KEY_LEFT_CONTROL = 94;
        private static int KEYBOARD_KEY_LEFT_WINDOWS = 95;
        private static int KEYBOARD_KEY_LEFT_ALT = 96;
        private static int KEYBOARD_KEY_JPN_MUHENKAN = 153;
        private static int KEYBOARD_KEY_SPACE = 97;
        private static int KEYBOARD_KEY_JPN_HENKAN = 154;
        private static int KEYBOARD_KEY_JPN_HIRAGANA_KATAKANA = 155;
        private static int KEYBOARD_KEY_RIGHT_ALT = 98;
        private static int KEYBOARD_KEY_RIGHT_WINDOWS = 99;
        private static int KEYBOARD_KEY_APPLICATION_SELECT = 100;
        private static int KEYBOARD_KEY_RIGHT_CONTROL = 101;
        private static int KEYBOARD_KEY_ARROW_LEFT = 102;
        private static int KEYBOARD_KEY_ARROW_DOWN = 103;
        private static int KEYBOARD_KEY_ARROW_RIGHT = 104;
        private static int KEYBOARD_KEY_NUM_ZERO = 105;
        private static int KEYBOARD_KEY_NUM_PERIOD = 106;
        private static int KEYBOARD_KEY_FN_Key = 107;
        private static int KEYBOARD_KEY_P1 = 108;
        private static int KEYBOARD_KEY_P2 = 109;
        private static int KEYBOARD_KEY_P3 = 110;
        private static int KEYBOARD_KEY_P4 = 111;
        private static int KEYBOARD_KEY_P5 = 112;
        private static int KEYBOARD_KEY_P6 = 113;
        private static int KEYBOARD_KEY_P7 = 114;
        private static int KEYBOARD_KEY_P8 = 115;
        private static int KEYBOARD_KEY_P9 = 116;
        private static int KEYBOARD_KEY_P10 = 117;
        private static int KEYBOARD_KEY_P11 = 118;
        private static int KEYBOARD_KEY_P12 = 119;
        private static int KEYBOARD_KEY_P13 = 120;
        private static int KEYBOARD_KEY_P14 = 121;
        private static int KEYBOARD_KEY_P15 = 122;
        private static int KEYBOARD_KEY_P16 = 123;
        private static int KEYBOARD_KEY_P17 = 124;
        private static int KEYBOARD_KEY_P18 = 125;
        private static int KEYBOARD_KEY_P19 = 126;
        private static int KEYBOARD_KEY_P20 = 127;
        private static int KEYBOARD_KEY_LOGO = 128;
        private static int KEYBOARD_KEY_LOGO2 = 129;
        private static int KEYBOARD_KEY_LOGO3 = 130;
        private static int KEYBOARD_KEY_BRIGHTNESS_SWITCH = 131;
        private static int KEYBOARD_KEY_LOCK_SWITCH = 132;
        private static int KEYBOARD_KEY_MEDIA_PLAY_PAUSE = 133;
        private static int KEYBOARD_KEY_MEDIA_PLAY = 134;
        private static int KEYBOARD_KEY_MEDIA_PAUSE = 135;
        private static int KEYBOARD_KEY_MEDIA_STOP = 136;
        private static int KEYBOARD_KEY_MEDIA_PREVIOUS = 137;
        private static int KEYBOARD_KEY_MEDIA_NEXT = 138;
        private static int KEYBOARD_KEY_VOLUME_MUTE = 139;
        private static int KEYBOARD_KEY_VOLUME_DOWN = 140;
        private static int KEYBOARD_KEY_VOLUME_UP = 141;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT1 = 142;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT2 = 143;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT3 = 144;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT4 = 145;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT5 = 146;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT6 = 147;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT7 = 148;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT8 = 149;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT9 = 150;
        private static int KEYBOARD_KEY_ADDITIONALLIGHT10 = 151;
        private static int KEYBOARD_KEY_INVALID = -1;

        static public int GetKey(DeviceKeys key)
        {
            if(key == DeviceKeys.HOME)
            {
                return KEYBOARD_KEY_LOGO;
            }
            return (int)key;
        }
    }
}
