using Aurora.Devices.Layout.Layouts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aurora.Devices.Razer
{
    public static class RazerLayoutMap
    {
        public static readonly Dictionary<KeyboardKeys, int[]> GenericKeyboard = new Dictionary<KeyboardKeys, int[]>
        {
            {KeyboardKeys.ESC, new int [] {0,1} },
            {KeyboardKeys.F1, new int [] {0, 3} },
            {KeyboardKeys.F2, new int [] {0, 4} },
            {KeyboardKeys.F3, new int [] {0, 5} },
            {KeyboardKeys.F4, new int [] {0, 6} },
            {KeyboardKeys.F5, new int [] {0, 7} },
            {KeyboardKeys.F6, new int [] {0, 8} },
            {KeyboardKeys.F7, new int [] {0, 9} },
            {KeyboardKeys.F8, new int [] {0, 10} },
            {KeyboardKeys.F9, new int [] {0, 11} },
            {KeyboardKeys.F10, new int [] {0, 12} },
            {KeyboardKeys.F11, new int [] {0, 13} },
            {KeyboardKeys.F12, new int [] {0, 14} },
            {KeyboardKeys.PRINT_SCREEN, new int [] {0, 15} },
            {KeyboardKeys.SCROLL_LOCK, new int [] {0, 16} },
            {KeyboardKeys.PAUSE_BREAK, new int [] {0, 17} },
            {KeyboardKeys.LOGO, new int [] {0, 20 } },
            {KeyboardKeys.G1, new int [] {1, 0} },
            {KeyboardKeys.TILDE, new int [] {1, 1} },
            {KeyboardKeys.ONE, new int [] {1, 2} },
            {KeyboardKeys.TWO, new int [] {1, 3} },
            {KeyboardKeys.THREE, new int [] {1, 4} },
            {KeyboardKeys.FOUR, new int [] {1, 5} },
            {KeyboardKeys.FIVE, new int [] {1, 6} },
            {KeyboardKeys.SIX, new int [] {1, 7} },
            {KeyboardKeys.SEVEN, new int [] {1, 8} },
            {KeyboardKeys.EIGHT, new int [] {1, 9} },
            {KeyboardKeys.NINE, new int [] {1, 10} },
            {KeyboardKeys.ZERO, new int [] {1, 11} },
            {KeyboardKeys.MINUS, new int [] {1, 12} },
            {KeyboardKeys.EQUALS, new int [] {1, 13} },
            {KeyboardKeys.BACKSPACE, new int [] {1, 14} },
            {KeyboardKeys.INSERT, new int [] {1, 15} },
            {KeyboardKeys.HOME, new int [] {1, 16} },
            {KeyboardKeys.PAGE_UP, new int [] {1, 17} },
            {KeyboardKeys.NUM_LOCK, new int [] {1, 18} },
            {KeyboardKeys.NUM_SLASH, new int [] {1, 19} },
            {KeyboardKeys.NUM_ASTERISK, new int [] {1, 20} },
            {KeyboardKeys.NUM_MINUS, new int [] {1, 21} },
            {KeyboardKeys.G2, new int [] {2, 0} },
            {KeyboardKeys.TAB, new int [] {2, 1} },
            {KeyboardKeys.Q, new int [] {2, 2} },
            {KeyboardKeys.W, new int [] {2, 3} },
            {KeyboardKeys.E, new int [] {2, 4} },
            {KeyboardKeys.R, new int [] {2, 5} },
            {KeyboardKeys.T, new int [] {2, 6} },
            {KeyboardKeys.Y, new int [] {2, 7} },
            {KeyboardKeys.U, new int [] {2, 8} },
            {KeyboardKeys.I, new int [] {2, 9} },
            {KeyboardKeys.O, new int [] {2, 10} },
            {KeyboardKeys.P, new int [] {2, 11} },
            {KeyboardKeys.OPEN_BRACKET, new int [] {2, 12} },
            {KeyboardKeys.CLOSE_BRACKET, new int [] {2,13} },
            {KeyboardKeys.BACKSLASH, new int [] {2, 14} },
            {KeyboardKeys.DELETE, new int [] {2, 15} },
            {KeyboardKeys.END, new int [] {2, 16} },
            {KeyboardKeys.PAGE_DOWN, new int [] {2, 17} },
            {KeyboardKeys.NUM_SEVEN, new int [] {2, 18} },
            {KeyboardKeys.NUM_EIGHT, new int [] {2, 19} },
            {KeyboardKeys.NUM_NINE, new int [] {2, 20} },
            {KeyboardKeys.NUM_PLUS, new int [] {2, 21} },
            {KeyboardKeys.G3, new int [] {3, 0} },
            {KeyboardKeys.CAPS_LOCK, new int [] {3, 1} },
            {KeyboardKeys.A, new int [] {3, 2} },
            {KeyboardKeys.S, new int [] {3, 3} },
            {KeyboardKeys.D, new int [] {3, 4} },
            {KeyboardKeys.F, new int [] {3, 5} },
            {KeyboardKeys.G, new int [] {3, 6} },
            {KeyboardKeys.H, new int [] {3, 7} },
            {KeyboardKeys.J, new int [] {3, 8} },
            {KeyboardKeys.K, new int [] {3, 9} },
            {KeyboardKeys.L, new int [] {3, 10} },
            {KeyboardKeys.SEMICOLON, new int [] {3, 11} },
            {KeyboardKeys.APOSTROPHE, new int [] {3, 12} },
            {KeyboardKeys.HASH, new int [] {3, 13} },
            {KeyboardKeys.ENTER, new int [] {3, 14} },
            {KeyboardKeys.NUM_FOUR, new int [] {3, 18} },
            {KeyboardKeys.NUM_FIVE, new int [] {3, 19} },
            {KeyboardKeys.NUM_SIX, new int [] {3, 20} },
            {KeyboardKeys.G4, new int [] {4, 0} },
            {KeyboardKeys.LEFT_SHIFT, new int [] {4, 1} },
            {KeyboardKeys.BACKSLASH_UK, new int [] {4, 2} },
            {KeyboardKeys.Z, new int [] {4, 3} },
            {KeyboardKeys.X, new int [] {4, 4} },
            {KeyboardKeys.C, new int [] {4, 5} },
            {KeyboardKeys.V, new int [] {4, 6} },
            {KeyboardKeys.B, new int [] {4, 7} },
            {KeyboardKeys.N, new int [] {4, 8} },
            {KeyboardKeys.M, new int [] {4, 9} },
            {KeyboardKeys.COMMA, new int [] {4, 10} },
            {KeyboardKeys.PERIOD, new int [] {4, 11} },
            {KeyboardKeys.FORWARD_SLASH, new int [] {4, 12} },
            {KeyboardKeys.RIGHT_SHIFT, new int [] {4, 14} },
            {KeyboardKeys.ARROW_UP, new int [] {4, 16} },
            {KeyboardKeys.NUM_ONE, new int [] {4, 18} },
            {KeyboardKeys.NUM_TWO, new int [] {4, 19} },
            {KeyboardKeys.NUM_THREE, new int [] {4, 20} },
            {KeyboardKeys.NUM_ENTER, new int [] {4, 21} },
            {KeyboardKeys.G5, new int [] {5, 0} },
            {KeyboardKeys.LEFT_CONTROL, new int [] {5, 1} },
            {KeyboardKeys.LEFT_WINDOWS, new int [] {5, 2} },
            {KeyboardKeys.LEFT_ALT, new int [] {5, 3} },
            {KeyboardKeys.SPACE, new int [] {5, 7} },
            {KeyboardKeys.RIGHT_ALT, new int [] {5, 11} },
            {KeyboardKeys.RIGHT_WINDOWS, new int [] {5, 12} },
            {KeyboardKeys.FN_Key, new int [] {5, 12} },
            {KeyboardKeys.APPLICATION_SELECT, new int [] {5, 13} },
            {KeyboardKeys.RIGHT_CONTROL, new int [] {5, 14} },
            {KeyboardKeys.ARROW_LEFT, new int [] {5, 15} },
            //{KeyboardKeys.ARROW_DOWN, new int [] {5, 16} },
            {KeyboardKeys.ARROW_RIGHT, new int [] {5, 17} },
            {KeyboardKeys.NUM_ZERO, new int [] {5, 19} },
            {KeyboardKeys.NUM_PERIOD, new int [] {5, 20} }
        };

        public static readonly Dictionary<KeyboardKeys, int[]> Blade = new Dictionary<KeyboardKeys, int[]>
        {
            {KeyboardKeys.ESC, new int [] {0,1} },
            {KeyboardKeys.F1, new int [] {0, 2} },
            {KeyboardKeys.F2, new int [] {0, 3} },
            {KeyboardKeys.F3, new int [] {0, 4} },
            {KeyboardKeys.F4, new int [] {0, 5} },
            {KeyboardKeys.F5, new int [] {0, 6} },
            {KeyboardKeys.F6, new int [] {0, 7} },
            {KeyboardKeys.F7, new int [] {0, 8} },
            {KeyboardKeys.F8, new int [] {0, 9} },
            {KeyboardKeys.F9, new int [] {0, 10} },
            {KeyboardKeys.F10, new int [] {0, 11} },
            {KeyboardKeys.F11, new int [] {0, 12} },
            {KeyboardKeys.F12, new int [] {0, 13} },
            {KeyboardKeys.INSERT, new int [] {0, 14} },
            {KeyboardKeys.DELETE, new int [] {0, 15} },
            {KeyboardKeys.TILDE, new int [] {1, 1} },
            {KeyboardKeys.ONE, new int [] {1, 2} },
            {KeyboardKeys.TWO, new int [] {1, 3} },
            {KeyboardKeys.THREE, new int [] {1, 4} },
            {KeyboardKeys.FOUR, new int [] {1, 5} },
            {KeyboardKeys.FIVE, new int [] {1, 6} },
            {KeyboardKeys.SIX, new int [] {1, 7} },
            {KeyboardKeys.SEVEN, new int [] {1, 8} },
            {KeyboardKeys.EIGHT, new int [] {1, 9} },
            {KeyboardKeys.NINE, new int [] {1, 10} },
            {KeyboardKeys.ZERO, new int [] {1, 11} },
            {KeyboardKeys.MINUS, new int [] {1, 12} },
            {KeyboardKeys.EQUALS, new int [] {1, 13} },
            {KeyboardKeys.BACKSPACE, new int [] {1, 15} },
            {KeyboardKeys.TAB, new int [] {2, 1} },
            {KeyboardKeys.Q, new int [] {2, 2} },
            {KeyboardKeys.W, new int [] {2, 3} },
            {KeyboardKeys.E, new int [] {2, 4} },
            {KeyboardKeys.R, new int [] {2, 5} },
            {KeyboardKeys.T, new int [] {2, 6} },
            {KeyboardKeys.Y, new int [] {2, 7} },
            {KeyboardKeys.U, new int [] {2, 8} },
            {KeyboardKeys.I, new int [] {2, 9} },
            {KeyboardKeys.O, new int [] {2, 10} },
            {KeyboardKeys.P, new int [] {2, 11} },
            {KeyboardKeys.OPEN_BRACKET, new int [] {2, 12} },
            {KeyboardKeys.CLOSE_BRACKET, new int [] {2, 13} },
            {KeyboardKeys.BACKSLASH, new int [] {2, 15} },
            {KeyboardKeys.BACKSLASH_UK, new int [] {2, 15} },
            {KeyboardKeys.CAPS_LOCK, new int [] {3, 1} },
            {KeyboardKeys.A, new int [] {3, 2} },
            {KeyboardKeys.S, new int [] {3, 3} },
            {KeyboardKeys.D, new int [] {3, 4} },
            {KeyboardKeys.F, new int [] {3, 5} },
            {KeyboardKeys.G, new int [] {3, 6} },
            {KeyboardKeys.H, new int [] {3, 7} },
            {KeyboardKeys.J, new int [] {3, 8} },
            {KeyboardKeys.K, new int [] {3, 9} },
            {KeyboardKeys.L, new int [] {3, 10} },
            {KeyboardKeys.SEMICOLON, new int [] {3, 11} },
            {KeyboardKeys.APOSTROPHE, new int [] {3, 12} },
            {KeyboardKeys.ENTER, new int [] {3, 15} },
            {KeyboardKeys.LEFT_SHIFT, new int [] {4, 1} },
            {KeyboardKeys.Z, new int [] {4, 3} },
            {KeyboardKeys.X, new int [] {4, 4} },
            {KeyboardKeys.C, new int [] {4, 5} },
            {KeyboardKeys.V, new int [] {4, 6} },
            {KeyboardKeys.B, new int [] {4, 7} },
            {KeyboardKeys.N, new int [] {4, 8} },
            {KeyboardKeys.M, new int [] {4, 9} },
            {KeyboardKeys.COMMA, new int [] {4, 10} },
            {KeyboardKeys.PERIOD, new int [] {4, 11} },
            {KeyboardKeys.FORWARD_SLASH, new int [] {4, 12} },
            {KeyboardKeys.RIGHT_SHIFT, new int [] {4, 15} },
            {KeyboardKeys.LEFT_CONTROL, new int [] {5, 1} },
            {KeyboardKeys.LEFT_FN, new int [] {5, 2} },
            {KeyboardKeys.LEFT_WINDOWS, new int [] {5, 3} },
            {KeyboardKeys.LEFT_ALT, new int [] {5, 4} },
            {KeyboardKeys.RIGHT_ALT, new int [] {5, 9} },
            {KeyboardKeys.FN_Key, new int [] {5, 10} },
            {KeyboardKeys.RIGHT_CONTROL, new int [] {5, 11} },
            {KeyboardKeys.ARROW_LEFT, new int [] {5, 12} },
            {KeyboardKeys.ARROW_UP, new int [] {5, 13} },
            {KeyboardKeys.ARROW_DOWN, new int [] {5, 14} },
            {KeyboardKeys.ARROW_RIGHT, new int [] {5, 15} }
        };
    }
}
