using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Aurora.Utils;
using CorsairRGB.NET.Enums;
using CorsairRGB.NET.Structures;

namespace Aurora.Devices.Corsair
{
    internal static class LedMaps
    {
        internal static readonly Dictionary<DeviceKeys, CorsairLedId> KeyboardLedMap = new Dictionary<DeviceKeys, CorsairLedId>()
        {
            [DeviceKeys.ESC] = CorsairLedId.K_Escape,
            [DeviceKeys.F1] = CorsairLedId.K_F1,
            [DeviceKeys.F2] = CorsairLedId.K_F2,
            [DeviceKeys.F3] = CorsairLedId.K_F3,
            [DeviceKeys.F4] = CorsairLedId.K_F4,
            [DeviceKeys.F5] = CorsairLedId.K_F5,
            [DeviceKeys.F6] = CorsairLedId.K_F6,
            [DeviceKeys.F7] = CorsairLedId.K_F7,
            [DeviceKeys.F8] = CorsairLedId.K_F8,
            [DeviceKeys.F9] = CorsairLedId.K_F9,
            [DeviceKeys.F10] = CorsairLedId.K_F10,
            [DeviceKeys.F11] = CorsairLedId.K_F11,
            [DeviceKeys.TILDE] = CorsairLedId.K_GraveAccentAndTilde,
            [DeviceKeys.ONE] = CorsairLedId.K_1,
            [DeviceKeys.TWO] = CorsairLedId.K_2,
            [DeviceKeys.THREE] = CorsairLedId.K_3,
            [DeviceKeys.FOUR] = CorsairLedId.K_4,
            [DeviceKeys.FIVE] = CorsairLedId.K_5,
            [DeviceKeys.SIX] = CorsairLedId.K_6,
            [DeviceKeys.SEVEN] = CorsairLedId.K_7,
            [DeviceKeys.EIGHT] = CorsairLedId.K_8,
            [DeviceKeys.NINE] = CorsairLedId.K_9,
            [DeviceKeys.ZERO] = CorsairLedId.K_0,
            [DeviceKeys.MINUS] = CorsairLedId.K_MinusAndUnderscore,
            [DeviceKeys.TAB] = CorsairLedId.K_Tab,
            [DeviceKeys.Q] = CorsairLedId.K_Q,
            [DeviceKeys.W] = CorsairLedId.K_W,
            [DeviceKeys.E] = CorsairLedId.K_E,
            [DeviceKeys.R] = CorsairLedId.K_R,
            [DeviceKeys.T] = CorsairLedId.K_T,
            [DeviceKeys.Y] = CorsairLedId.K_Y,
            [DeviceKeys.U] = CorsairLedId.K_U,
            [DeviceKeys.I] = CorsairLedId.K_I,
            [DeviceKeys.O] = CorsairLedId.K_O,
            [DeviceKeys.P] = CorsairLedId.K_P,
            [DeviceKeys.OPEN_BRACKET] = CorsairLedId.K_BracketLeft,
            [DeviceKeys.CAPS_LOCK] = CorsairLedId.K_CapsLock,
            [DeviceKeys.A] = CorsairLedId.K_A,
            [DeviceKeys.S] = CorsairLedId.K_S,
            [DeviceKeys.D] = CorsairLedId.K_D,
            [DeviceKeys.F] = CorsairLedId.K_F,
            [DeviceKeys.G] = CorsairLedId.K_G,
            [DeviceKeys.H] = CorsairLedId.K_H,
            [DeviceKeys.J] = CorsairLedId.K_J,
            [DeviceKeys.K] = CorsairLedId.K_K,
            [DeviceKeys.L] = CorsairLedId.K_L,
            [DeviceKeys.SEMICOLON] = CorsairLedId.K_SemicolonAndColon,
            [DeviceKeys.APOSTROPHE] = CorsairLedId.K_ApostropheAndDoubleQuote,
            [DeviceKeys.LEFT_SHIFT] = CorsairLedId.K_LeftShift,
            [DeviceKeys.BACKSLASH_UK] = CorsairLedId.K_NonUsBackslash,
            [DeviceKeys.Z] = CorsairLedId.K_Z,
            [DeviceKeys.X] = CorsairLedId.K_X,
            [DeviceKeys.C] = CorsairLedId.K_C,
            [DeviceKeys.V] = CorsairLedId.K_V,
            [DeviceKeys.B] = CorsairLedId.K_B,
            [DeviceKeys.N] = CorsairLedId.K_N,
            [DeviceKeys.M] = CorsairLedId.K_M,
            [DeviceKeys.COMMA] = CorsairLedId.K_CommaAndLessThan,
            [DeviceKeys.PERIOD] = CorsairLedId.K_PeriodAndBiggerThan,
            [DeviceKeys.FORWARD_SLASH] = CorsairLedId.K_SlashAndQuestionMark,
            [DeviceKeys.LEFT_CONTROL] = CorsairLedId.K_LeftCtrl,
            [DeviceKeys.LEFT_WINDOWS] = CorsairLedId.K_LeftGui,
            [DeviceKeys.LEFT_ALT] = CorsairLedId.K_LeftAlt,
            //[DeviceKeys.Lang2] = CorsairLedId.K_Lang2,
            [DeviceKeys.SPACE] = CorsairLedId.K_Space,
            //[DeviceKeys.Lang1] = CorsairLedId.K_Lang1,
            //[DeviceKeys.International2] = CorsairLedId.K_International2,
            [DeviceKeys.RIGHT_ALT] = CorsairLedId.K_RightAlt,
            [DeviceKeys.RIGHT_WINDOWS] = CorsairLedId.K_RightGui,
            [DeviceKeys.APPLICATION_SELECT] = CorsairLedId.K_Application,
            //[DeviceKeys.LedProgramming] = CorsairLedId.K_LedProgramming,
            [DeviceKeys.BRIGHTNESS_SWITCH] = CorsairLedId.K_Brightness,
            [DeviceKeys.F12] = CorsairLedId.K_F12,
            [DeviceKeys.PRINT_SCREEN] = CorsairLedId.K_PrintScreen,
            [DeviceKeys.SCROLL_LOCK] = CorsairLedId.K_ScrollLock,
            [DeviceKeys.PAUSE_BREAK] = CorsairLedId.K_PauseBreak,
            [DeviceKeys.INSERT] = CorsairLedId.K_Insert,
            [DeviceKeys.HOME] = CorsairLedId.K_Home,
            [DeviceKeys.PAGE_UP] = CorsairLedId.K_PageUp,
            [DeviceKeys.CLOSE_BRACKET] = CorsairLedId.K_BracketRight,
            [DeviceKeys.BACKSLASH] = CorsairLedId.K_Backslash,
            [DeviceKeys.HASHTAG] = CorsairLedId.K_NonUsTilde,
            [DeviceKeys.ENTER] = CorsairLedId.K_Enter,
            //[DeviceKeys.International1] = CorsairLedId.K_International1,
            [DeviceKeys.EQUALS] = CorsairLedId.K_EqualsAndPlus,
            //[DeviceKeys.International3] = CorsairLedId.K_International3,
            [DeviceKeys.BACKSPACE] = CorsairLedId.K_Backspace,
            [DeviceKeys.DELETE] = CorsairLedId.K_Delete,
            [DeviceKeys.END] = CorsairLedId.K_End,
            [DeviceKeys.PAGE_DOWN] = CorsairLedId.K_PageDown,
            [DeviceKeys.RIGHT_SHIFT] = CorsairLedId.K_RightShift,
            [DeviceKeys.RIGHT_CONTROL] = CorsairLedId.K_RightCtrl,
            [DeviceKeys.ARROW_UP] = CorsairLedId.K_UpArrow,
            [DeviceKeys.ARROW_LEFT] = CorsairLedId.K_LeftArrow,
            [DeviceKeys.ARROW_DOWN] = CorsairLedId.K_DownArrow,
            [DeviceKeys.ARROW_RIGHT] = CorsairLedId.K_RightArrow,
            [DeviceKeys.LOCK_SWITCH] = CorsairLedId.K_WinLock,
            [DeviceKeys.VOLUME_MUTE] = CorsairLedId.K_Mute,
            [DeviceKeys.MEDIA_STOP] = CorsairLedId.K_Stop,
            [DeviceKeys.MEDIA_PREVIOUS] = CorsairLedId.K_ScanPreviousTrack,
            [DeviceKeys.MEDIA_PLAY_PAUSE] = CorsairLedId.K_PlayPause,
            [DeviceKeys.MEDIA_NEXT] = CorsairLedId.K_ScanNextTrack,
            [DeviceKeys.NUM_LOCK] = CorsairLedId.K_NumLock,
            [DeviceKeys.NUM_SLASH] = CorsairLedId.K_KeypadSlash,
            [DeviceKeys.NUM_ASTERISK] = CorsairLedId.K_KeypadAsterisk,
            [DeviceKeys.NUM_MINUS] = CorsairLedId.K_KeypadMinus,
            [DeviceKeys.NUM_PLUS] = CorsairLedId.K_KeypadPlus,
            [DeviceKeys.NUM_ENTER] = CorsairLedId.K_KeypadEnter,
            [DeviceKeys.NUM_SEVEN] = CorsairLedId.K_Keypad7,
            [DeviceKeys.NUM_EIGHT] = CorsairLedId.K_Keypad8,
            [DeviceKeys.NUM_NINE] = CorsairLedId.K_Keypad9,
            [DeviceKeys.NUM_ZEROZERO] = CorsairLedId.K_KeypadComma,
            [DeviceKeys.NUM_FOUR] = CorsairLedId.K_Keypad4,
            [DeviceKeys.NUM_FIVE] = CorsairLedId.K_Keypad5,
            [DeviceKeys.NUM_SIX] = CorsairLedId.K_Keypad6,
            [DeviceKeys.NUM_ONE] = CorsairLedId.K_Keypad1,
            [DeviceKeys.NUM_TWO] = CorsairLedId.K_Keypad2,
            [DeviceKeys.NUM_THREE] = CorsairLedId.K_Keypad3,
            [DeviceKeys.NUM_ZERO] = CorsairLedId.K_Keypad0,
            [DeviceKeys.NUM_PERIOD] = CorsairLedId.K_KeypadPeriodAndDelete,
            [DeviceKeys.G1] = CorsairLedId.K_G1,
            [DeviceKeys.G2] = CorsairLedId.K_G2,
            [DeviceKeys.G3] = CorsairLedId.K_G3,
            [DeviceKeys.G4] = CorsairLedId.K_G4,
            [DeviceKeys.G5] = CorsairLedId.K_G5,
            [DeviceKeys.G6] = CorsairLedId.K_G6,
            [DeviceKeys.G7] = CorsairLedId.K_G7,
            [DeviceKeys.G8] = CorsairLedId.K_G8,
            [DeviceKeys.G9] = CorsairLedId.K_G9,
            [DeviceKeys.G10] = CorsairLedId.K_G10,
            [DeviceKeys.VOLUME_UP] = CorsairLedId.K_VolumeUp,
            [DeviceKeys.VOLUME_DOWN] = CorsairLedId.K_VolumeDown,
            //[DeviceKeys.MR] = CorsairLedId.K_MR,
            //[DeviceKeys.M1] = CorsairLedId.K_M1,
            //[DeviceKeys.M2] = CorsairLedId.K_M2,
            //[DeviceKeys.M3] = CorsairLedId.K_M3,
            [DeviceKeys.G11] = CorsairLedId.K_G11,
            [DeviceKeys.G12] = CorsairLedId.K_G12,
            [DeviceKeys.G13] = CorsairLedId.K_G13,
            [DeviceKeys.G14] = CorsairLedId.K_G14,
            [DeviceKeys.G15] = CorsairLedId.K_G15,
            [DeviceKeys.G16] = CorsairLedId.K_G16,
            [DeviceKeys.G17] = CorsairLedId.K_G17,
            [DeviceKeys.G18] = CorsairLedId.K_G18,
            //[DeviceKeys.International5] = CorsairLedId.K_International5,
            //[DeviceKeys.International4] = CorsairLedId.K_International4,
            [DeviceKeys.FN_Key] = CorsairLedId.K_Fn,
            [DeviceKeys.LOCK_SWITCH] = CorsairLedId.K_WinLock,
            [DeviceKeys.BRIGHTNESS_SWITCH] = CorsairLedId.K_Brightness,
            [DeviceKeys.ADDITIONALLIGHT1] = CorsairLedId.KLP_Zone1,
            [DeviceKeys.ADDITIONALLIGHT2] = CorsairLedId.KLP_Zone2,
            [DeviceKeys.ADDITIONALLIGHT3] = CorsairLedId.KLP_Zone3,
            [DeviceKeys.ADDITIONALLIGHT4] = CorsairLedId.KLP_Zone4,
            [DeviceKeys.ADDITIONALLIGHT5] = CorsairLedId.KLP_Zone5,
            [DeviceKeys.ADDITIONALLIGHT6] = CorsairLedId.KLP_Zone6,
            [DeviceKeys.ADDITIONALLIGHT7] = CorsairLedId.KLP_Zone7,
            [DeviceKeys.ADDITIONALLIGHT8] = CorsairLedId.KLP_Zone8,
            [DeviceKeys.ADDITIONALLIGHT9] = CorsairLedId.KLP_Zone9,
            [DeviceKeys.ADDITIONALLIGHT10] = CorsairLedId.KLP_Zone10,
            [DeviceKeys.ADDITIONALLIGHT11] = CorsairLedId.KLP_Zone11,
            [DeviceKeys.ADDITIONALLIGHT12] = CorsairLedId.KLP_Zone12,
            [DeviceKeys.ADDITIONALLIGHT13] = CorsairLedId.KLP_Zone13,
            [DeviceKeys.ADDITIONALLIGHT14] = CorsairLedId.KLP_Zone14,
            [DeviceKeys.ADDITIONALLIGHT15] = CorsairLedId.KLP_Zone15,
            [DeviceKeys.ADDITIONALLIGHT16] = CorsairLedId.KLP_Zone16,
            [DeviceKeys.ADDITIONALLIGHT17] = CorsairLedId.KLP_Zone17,
            [DeviceKeys.ADDITIONALLIGHT18] = CorsairLedId.KLP_Zone18,
            [DeviceKeys.ADDITIONALLIGHT19] = CorsairLedId.KLP_Zone19
        };

        internal static readonly Dictionary<DeviceKeys, CorsairLedId> MouseLedMap = new Dictionary<DeviceKeys, CorsairLedId>()
        {
            [DeviceKeys.Peripheral_Logo] = CorsairLedId.M_1,
            [DeviceKeys.Peripheral_FrontLight] = CorsairLedId.M_2,
            [DeviceKeys.Peripheral_ScrollWheel] = CorsairLedId.M_3,
            [DeviceKeys.ADDITIONALLIGHT1] = CorsairLedId.M_4,//TODO
            [DeviceKeys.ADDITIONALLIGHT2] = CorsairLedId.M_5,
            [DeviceKeys.ADDITIONALLIGHT3] = CorsairLedId.M_6
        };

        internal static readonly Dictionary<DeviceKeys, CorsairLedId> MouseMatLedMap = new Dictionary<DeviceKeys, CorsairLedId>()
        {
            [DeviceKeys.MOUSEPADLIGHT1] = CorsairLedId.MM_Zone1,
            [DeviceKeys.MOUSEPADLIGHT2] = CorsairLedId.MM_Zone2,
            [DeviceKeys.MOUSEPADLIGHT3] = CorsairLedId.MM_Zone3,
            [DeviceKeys.MOUSEPADLIGHT4] = CorsairLedId.MM_Zone4,
            [DeviceKeys.MOUSEPADLIGHT5] = CorsairLedId.MM_Zone5,
            [DeviceKeys.MOUSEPADLIGHT6] = CorsairLedId.MM_Zone6,
            [DeviceKeys.MOUSEPADLIGHT7] = CorsairLedId.MM_Zone7,
            [DeviceKeys.MOUSEPADLIGHT8] = CorsairLedId.MM_Zone8,
            [DeviceKeys.MOUSEPADLIGHT9] = CorsairLedId.MM_Zone9,
            [DeviceKeys.MOUSEPADLIGHT10] = CorsairLedId.MM_Zone10,
            [DeviceKeys.MOUSEPADLIGHT11] = CorsairLedId.MM_Zone11,
            [DeviceKeys.MOUSEPADLIGHT12] = CorsairLedId.MM_Zone12,
            [DeviceKeys.MOUSEPADLIGHT13] = CorsairLedId.MM_Zone13,
            [DeviceKeys.MOUSEPADLIGHT14] = CorsairLedId.MM_Zone14,
            [DeviceKeys.MOUSEPADLIGHT15] = CorsairLedId.MM_Zone15
        };

        internal static readonly Dictionary<DeviceKeys, CorsairLedId> HeadsetStandLedMap = new Dictionary<DeviceKeys, CorsairLedId>()
        {
            [DeviceKeys.Peripheral_Logo] = CorsairLedId.HSS_Zone1,
            [DeviceKeys.MOUSEPADLIGHT15] = CorsairLedId.HSS_Zone2,
            [DeviceKeys.MOUSEPADLIGHT13] = CorsairLedId.HSS_Zone3,
            [DeviceKeys.MOUSEPADLIGHT11] = CorsairLedId.HSS_Zone4,
            [DeviceKeys.MOUSEPADLIGHT9] = CorsairLedId.HSS_Zone5,
            [DeviceKeys.MOUSEPADLIGHT7] = CorsairLedId.HSS_Zone6,
            [DeviceKeys.MOUSEPADLIGHT5] = CorsairLedId.HSS_Zone7,
            [DeviceKeys.MOUSEPADLIGHT3] = CorsairLedId.HSS_Zone8,
            [DeviceKeys.MOUSEPADLIGHT1] = CorsairLedId.HSS_Zone9,
        };

        internal static readonly Dictionary<DeviceKeys, CorsairLedId> HeadsetLedMap = new Dictionary<DeviceKeys, CorsairLedId>()
        {
            [DeviceKeys.Peripheral_FrontLight] = CorsairLedId.H_LeftLogo,//TODO
            [DeviceKeys.Peripheral_ScrollWheel] = CorsairLedId.H_RightLogo
        };

        internal static readonly Dictionary<CorsairDeviceType, Dictionary<DeviceKeys, CorsairLedId>> MapsMap = new Dictionary<CorsairDeviceType, Dictionary<DeviceKeys, CorsairLedId>>()
        {
            [CorsairDeviceType.Keyboard] = KeyboardLedMap,
            [CorsairDeviceType.Mouse] = MouseLedMap,
            [CorsairDeviceType.MouseMat] = MouseMatLedMap,
            [CorsairDeviceType.HeadsetStand] = HeadsetStandLedMap,
            [CorsairDeviceType.Headset] = HeadsetLedMap,
        };

        internal static readonly List<CorsairLedId> DIYLeds = new List<CorsairLedId>()
        {
            #region Channel 1
            CorsairLedId.D_C1_1,
            CorsairLedId.D_C1_2,
            CorsairLedId.D_C1_3,
            CorsairLedId.D_C1_4,
            CorsairLedId.D_C1_5,
            CorsairLedId.D_C1_6,
            CorsairLedId.D_C1_7,
            CorsairLedId.D_C1_8,
            CorsairLedId.D_C1_9,
            CorsairLedId.D_C1_10,
            CorsairLedId.D_C1_11,
            CorsairLedId.D_C1_12,
            CorsairLedId.D_C1_13,
            CorsairLedId.D_C1_14,
            CorsairLedId.D_C1_15,
            CorsairLedId.D_C1_16,
            CorsairLedId.D_C1_17,
            CorsairLedId.D_C1_18,
            CorsairLedId.D_C1_19,
            CorsairLedId.D_C1_20,
            CorsairLedId.D_C1_21,
            CorsairLedId.D_C1_22,
            CorsairLedId.D_C1_23,
            CorsairLedId.D_C1_24,
            CorsairLedId.D_C1_25,
            CorsairLedId.D_C1_26,
            CorsairLedId.D_C1_27,
            CorsairLedId.D_C1_28,
            CorsairLedId.D_C1_29,
            CorsairLedId.D_C1_30,
            CorsairLedId.D_C1_31,
            CorsairLedId.D_C1_32,
            CorsairLedId.D_C1_33,
            CorsairLedId.D_C1_34,
            CorsairLedId.D_C1_35,
            CorsairLedId.D_C1_36,
            CorsairLedId.D_C1_37,
            CorsairLedId.D_C1_38,
            CorsairLedId.D_C1_39,
            CorsairLedId.D_C1_40,
            CorsairLedId.D_C1_41,
            CorsairLedId.D_C1_42,
            CorsairLedId.D_C1_43,
            CorsairLedId.D_C1_44,
            CorsairLedId.D_C1_45,
            CorsairLedId.D_C1_46,
            CorsairLedId.D_C1_47,
            CorsairLedId.D_C1_48,
            CorsairLedId.D_C1_49,
            CorsairLedId.D_C1_50,
            CorsairLedId.D_C1_51,
            CorsairLedId.D_C1_52,
            CorsairLedId.D_C1_53,
            CorsairLedId.D_C1_54,
            CorsairLedId.D_C1_55,
            CorsairLedId.D_C1_56,
            CorsairLedId.D_C1_57,
            CorsairLedId.D_C1_58,
            CorsairLedId.D_C1_59,
            CorsairLedId.D_C1_60,
            CorsairLedId.D_C1_61,
            CorsairLedId.D_C1_62,
            CorsairLedId.D_C1_63,
            CorsairLedId.D_C1_64,
            CorsairLedId.D_C1_65,
            CorsairLedId.D_C1_66,
            CorsairLedId.D_C1_67,
            CorsairLedId.D_C1_68,
            CorsairLedId.D_C1_69,
            CorsairLedId.D_C1_70,
            CorsairLedId.D_C1_71,
            CorsairLedId.D_C1_72,
            CorsairLedId.D_C1_73,
            CorsairLedId.D_C1_74,
            CorsairLedId.D_C1_75,
            CorsairLedId.D_C1_76,
            CorsairLedId.D_C1_77,
            CorsairLedId.D_C1_78,
            CorsairLedId.D_C1_79,
            CorsairLedId.D_C1_80,
            CorsairLedId.D_C1_81,
            CorsairLedId.D_C1_82,
            CorsairLedId.D_C1_83,
            CorsairLedId.D_C1_84,
            CorsairLedId.D_C1_85,
            CorsairLedId.D_C1_86,
            CorsairLedId.D_C1_87,
            CorsairLedId.D_C1_88,
            CorsairLedId.D_C1_89,
            CorsairLedId.D_C1_90,
            CorsairLedId.D_C1_91,
            CorsairLedId.D_C1_92,
            CorsairLedId.D_C1_93,
            CorsairLedId.D_C1_94,
            CorsairLedId.D_C1_95,
            CorsairLedId.D_C1_96,
            CorsairLedId.D_C1_97,
            CorsairLedId.D_C1_98,
            CorsairLedId.D_C1_99,
            CorsairLedId.D_C1_100,
            CorsairLedId.D_C1_101,
            CorsairLedId.D_C1_102,
            CorsairLedId.D_C1_103,
            CorsairLedId.D_C1_104,
            CorsairLedId.D_C1_105,
            CorsairLedId.D_C1_106,
            CorsairLedId.D_C1_107,
            CorsairLedId.D_C1_108,
            CorsairLedId.D_C1_109,
            CorsairLedId.D_C1_110,
            CorsairLedId.D_C1_111,
            CorsairLedId.D_C1_112,
            CorsairLedId.D_C1_113,
            CorsairLedId.D_C1_114,
            CorsairLedId.D_C1_115,
            CorsairLedId.D_C1_116,
            CorsairLedId.D_C1_117,
            CorsairLedId.D_C1_118,
            CorsairLedId.D_C1_119,
            CorsairLedId.D_C1_120,
            CorsairLedId.D_C1_121,
            CorsairLedId.D_C1_122,
            CorsairLedId.D_C1_123,
            CorsairLedId.D_C1_124,
            CorsairLedId.D_C1_125,
            CorsairLedId.D_C1_126,
            CorsairLedId.D_C1_127,
            CorsairLedId.D_C1_128,
            CorsairLedId.D_C1_129,
            CorsairLedId.D_C1_130,
            CorsairLedId.D_C1_131,
            CorsairLedId.D_C1_132,
            CorsairLedId.D_C1_133,
            CorsairLedId.D_C1_134,
            CorsairLedId.D_C1_135,
            CorsairLedId.D_C1_136,
            CorsairLedId.D_C1_137,
            CorsairLedId.D_C1_138,
            CorsairLedId.D_C1_139,
            CorsairLedId.D_C1_140,
            CorsairLedId.D_C1_141,
            CorsairLedId.D_C1_142,
            CorsairLedId.D_C1_143,
            CorsairLedId.D_C1_144,
            CorsairLedId.D_C1_145,
            CorsairLedId.D_C1_146,
            CorsairLedId.D_C1_147,
            CorsairLedId.D_C1_148,
            CorsairLedId.D_C1_149,
            CorsairLedId.D_C1_150,
            #endregion
            #region Channel 2
            CorsairLedId.D_C2_1,
            CorsairLedId.D_C2_2,
            CorsairLedId.D_C2_3,
            CorsairLedId.D_C2_4,
            CorsairLedId.D_C2_5,
            CorsairLedId.D_C2_6,
            CorsairLedId.D_C2_7,
            CorsairLedId.D_C2_8,
            CorsairLedId.D_C2_9,
            CorsairLedId.D_C2_10,
            CorsairLedId.D_C2_11,
            CorsairLedId.D_C2_12,
            CorsairLedId.D_C2_13,
            CorsairLedId.D_C2_14,
            CorsairLedId.D_C2_15,
            CorsairLedId.D_C2_16,
            CorsairLedId.D_C2_17,
            CorsairLedId.D_C2_18,
            CorsairLedId.D_C2_19,
            CorsairLedId.D_C2_20,
            CorsairLedId.D_C2_21,
            CorsairLedId.D_C2_22,
            CorsairLedId.D_C2_23,
            CorsairLedId.D_C2_24,
            CorsairLedId.D_C2_25,
            CorsairLedId.D_C2_26,
            CorsairLedId.D_C2_27,
            CorsairLedId.D_C2_28,
            CorsairLedId.D_C2_29,
            CorsairLedId.D_C2_30,
            CorsairLedId.D_C2_31,
            CorsairLedId.D_C2_32,
            CorsairLedId.D_C2_33,
            CorsairLedId.D_C2_34,
            CorsairLedId.D_C2_35,
            CorsairLedId.D_C2_36,
            CorsairLedId.D_C2_37,
            CorsairLedId.D_C2_38,
            CorsairLedId.D_C2_39,
            CorsairLedId.D_C2_40,
            CorsairLedId.D_C2_41,
            CorsairLedId.D_C2_42,
            CorsairLedId.D_C2_43,
            CorsairLedId.D_C2_44,
            CorsairLedId.D_C2_45,
            CorsairLedId.D_C2_46,
            CorsairLedId.D_C2_47,
            CorsairLedId.D_C2_48,
            CorsairLedId.D_C2_49,
            CorsairLedId.D_C2_50,
            CorsairLedId.D_C2_51,
            CorsairLedId.D_C2_52,
            CorsairLedId.D_C2_53,
            CorsairLedId.D_C2_54,
            CorsairLedId.D_C2_55,
            CorsairLedId.D_C2_56,
            CorsairLedId.D_C2_57,
            CorsairLedId.D_C2_58,
            CorsairLedId.D_C2_59,
            CorsairLedId.D_C2_60,
            CorsairLedId.D_C2_61,
            CorsairLedId.D_C2_62,
            CorsairLedId.D_C2_63,
            CorsairLedId.D_C2_64,
            CorsairLedId.D_C2_65,
            CorsairLedId.D_C2_66,
            CorsairLedId.D_C2_67,
            CorsairLedId.D_C2_68,
            CorsairLedId.D_C2_69,
            CorsairLedId.D_C2_70,
            CorsairLedId.D_C2_71,
            CorsairLedId.D_C2_72,
            CorsairLedId.D_C2_73,
            CorsairLedId.D_C2_74,
            CorsairLedId.D_C2_75,
            CorsairLedId.D_C2_76,
            CorsairLedId.D_C2_77,
            CorsairLedId.D_C2_78,
            CorsairLedId.D_C2_79,
            CorsairLedId.D_C2_80,
            CorsairLedId.D_C2_81,
            CorsairLedId.D_C2_82,
            CorsairLedId.D_C2_83,
            CorsairLedId.D_C2_84,
            CorsairLedId.D_C2_85,
            CorsairLedId.D_C2_86,
            CorsairLedId.D_C2_87,
            CorsairLedId.D_C2_88,
            CorsairLedId.D_C2_89,
            CorsairLedId.D_C2_90,
            CorsairLedId.D_C2_91,
            CorsairLedId.D_C2_92,
            CorsairLedId.D_C2_93,
            CorsairLedId.D_C2_94,
            CorsairLedId.D_C2_95,
            CorsairLedId.D_C2_96,
            CorsairLedId.D_C2_97,
            CorsairLedId.D_C2_98,
            CorsairLedId.D_C2_99,
            CorsairLedId.D_C2_100,
            CorsairLedId.D_C2_101,
            CorsairLedId.D_C2_102,
            CorsairLedId.D_C2_103,
            CorsairLedId.D_C2_104,
            CorsairLedId.D_C2_105,
            CorsairLedId.D_C2_106,
            CorsairLedId.D_C2_107,
            CorsairLedId.D_C2_108,
            CorsairLedId.D_C2_109,
            CorsairLedId.D_C2_110,
            CorsairLedId.D_C2_111,
            CorsairLedId.D_C2_112,
            CorsairLedId.D_C2_113,
            CorsairLedId.D_C2_114,
            CorsairLedId.D_C2_115,
            CorsairLedId.D_C2_116,
            CorsairLedId.D_C2_117,
            CorsairLedId.D_C2_118,
            CorsairLedId.D_C2_119,
            CorsairLedId.D_C2_120,
            CorsairLedId.D_C2_121,
            CorsairLedId.D_C2_122,
            CorsairLedId.D_C2_123,
            CorsairLedId.D_C2_124,
            CorsairLedId.D_C2_125,
            CorsairLedId.D_C2_126,
            CorsairLedId.D_C2_127,
            CorsairLedId.D_C2_128,
            CorsairLedId.D_C2_129,
            CorsairLedId.D_C2_130,
            CorsairLedId.D_C2_131,
            CorsairLedId.D_C2_132,
            CorsairLedId.D_C2_133,
            CorsairLedId.D_C2_134,
            CorsairLedId.D_C2_135,
            CorsairLedId.D_C2_136,
            CorsairLedId.D_C2_137,
            CorsairLedId.D_C2_138,
            CorsairLedId.D_C2_139,
            CorsairLedId.D_C2_140,
            CorsairLedId.D_C2_141,
            CorsairLedId.D_C2_142,
            CorsairLedId.D_C2_143,
            CorsairLedId.D_C2_144,
            CorsairLedId.D_C2_145,
            CorsairLedId.D_C2_146,
            CorsairLedId.D_C2_147,
            CorsairLedId.D_C2_148,
            CorsairLedId.D_C2_149,
            CorsairLedId.D_C2_150,
            #endregion
            #region Channel 3
            CorsairLedId.D_C3_1,
            CorsairLedId.D_C3_2,
            CorsairLedId.D_C3_3,
            CorsairLedId.D_C3_4,
            CorsairLedId.D_C3_5,
            CorsairLedId.D_C3_6,
            CorsairLedId.D_C3_7,
            CorsairLedId.D_C3_8,
            CorsairLedId.D_C3_9,
            CorsairLedId.D_C3_10,
            CorsairLedId.D_C3_11,
            CorsairLedId.D_C3_12,
            CorsairLedId.D_C3_13,
            CorsairLedId.D_C3_14,
            CorsairLedId.D_C3_15,
            CorsairLedId.D_C3_16,
            CorsairLedId.D_C3_17,
            CorsairLedId.D_C3_18,
            CorsairLedId.D_C3_19,
            CorsairLedId.D_C3_20,
            CorsairLedId.D_C3_21,
            CorsairLedId.D_C3_22,
            CorsairLedId.D_C3_23,
            CorsairLedId.D_C3_24,
            CorsairLedId.D_C3_25,
            CorsairLedId.D_C3_26,
            CorsairLedId.D_C3_27,
            CorsairLedId.D_C3_28,
            CorsairLedId.D_C3_29,
            CorsairLedId.D_C3_30,
            CorsairLedId.D_C3_31,
            CorsairLedId.D_C3_32,
            CorsairLedId.D_C3_33,
            CorsairLedId.D_C3_34,
            CorsairLedId.D_C3_35,
            CorsairLedId.D_C3_36,
            CorsairLedId.D_C3_37,
            CorsairLedId.D_C3_38,
            CorsairLedId.D_C3_39,
            CorsairLedId.D_C3_40,
            CorsairLedId.D_C3_41,
            CorsairLedId.D_C3_42,
            CorsairLedId.D_C3_43,
            CorsairLedId.D_C3_44,
            CorsairLedId.D_C3_45,
            CorsairLedId.D_C3_46,
            CorsairLedId.D_C3_47,
            CorsairLedId.D_C3_48,
            CorsairLedId.D_C3_49,
            CorsairLedId.D_C3_50,
            CorsairLedId.D_C3_51,
            CorsairLedId.D_C3_52,
            CorsairLedId.D_C3_53,
            CorsairLedId.D_C3_54,
            CorsairLedId.D_C3_55,
            CorsairLedId.D_C3_56,
            CorsairLedId.D_C3_57,
            CorsairLedId.D_C3_58,
            CorsairLedId.D_C3_59,
            CorsairLedId.D_C3_60,
            CorsairLedId.D_C3_61,
            CorsairLedId.D_C3_62,
            CorsairLedId.D_C3_63,
            CorsairLedId.D_C3_64,
            CorsairLedId.D_C3_65,
            CorsairLedId.D_C3_66,
            CorsairLedId.D_C3_67,
            CorsairLedId.D_C3_68,
            CorsairLedId.D_C3_69,
            CorsairLedId.D_C3_70,
            CorsairLedId.D_C3_71,
            CorsairLedId.D_C3_72,
            CorsairLedId.D_C3_73,
            CorsairLedId.D_C3_74,
            CorsairLedId.D_C3_75,
            CorsairLedId.D_C3_76,
            CorsairLedId.D_C3_77,
            CorsairLedId.D_C3_78,
            CorsairLedId.D_C3_79,
            CorsairLedId.D_C3_80,
            CorsairLedId.D_C3_81,
            CorsairLedId.D_C3_82,
            CorsairLedId.D_C3_83,
            CorsairLedId.D_C3_84,
            CorsairLedId.D_C3_85,
            CorsairLedId.D_C3_86,
            CorsairLedId.D_C3_87,
            CorsairLedId.D_C3_88,
            CorsairLedId.D_C3_89,
            CorsairLedId.D_C3_90,
            CorsairLedId.D_C3_91,
            CorsairLedId.D_C3_92,
            CorsairLedId.D_C3_93,
            CorsairLedId.D_C3_94,
            CorsairLedId.D_C3_95,
            CorsairLedId.D_C3_96,
            CorsairLedId.D_C3_97,
            CorsairLedId.D_C3_98,
            CorsairLedId.D_C3_99,
            CorsairLedId.D_C3_100,
            CorsairLedId.D_C3_101,
            CorsairLedId.D_C3_102,
            CorsairLedId.D_C3_103,
            CorsairLedId.D_C3_104,
            CorsairLedId.D_C3_105,
            CorsairLedId.D_C3_106,
            CorsairLedId.D_C3_107,
            CorsairLedId.D_C3_108,
            CorsairLedId.D_C3_109,
            CorsairLedId.D_C3_110,
            CorsairLedId.D_C3_111,
            CorsairLedId.D_C3_112,
            CorsairLedId.D_C3_113,
            CorsairLedId.D_C3_114,
            CorsairLedId.D_C3_115,
            CorsairLedId.D_C3_116,
            CorsairLedId.D_C3_117,
            CorsairLedId.D_C3_118,
            CorsairLedId.D_C3_119,
            CorsairLedId.D_C3_120,
            CorsairLedId.D_C3_121,
            CorsairLedId.D_C3_122,
            CorsairLedId.D_C3_123,
            CorsairLedId.D_C3_124,
            CorsairLedId.D_C3_125,
            CorsairLedId.D_C3_126,
            CorsairLedId.D_C3_127,
            CorsairLedId.D_C3_128,
            CorsairLedId.D_C3_129,
            CorsairLedId.D_C3_130,
            CorsairLedId.D_C3_131,
            CorsairLedId.D_C3_132,
            CorsairLedId.D_C3_133,
            CorsairLedId.D_C3_134,
            CorsairLedId.D_C3_135,
            CorsairLedId.D_C3_136,
            CorsairLedId.D_C3_137,
            CorsairLedId.D_C3_138,
            CorsairLedId.D_C3_139,
            CorsairLedId.D_C3_140,
            CorsairLedId.D_C3_141,
            CorsairLedId.D_C3_142,
            CorsairLedId.D_C3_143,
            CorsairLedId.D_C3_144,
            CorsairLedId.D_C3_145,
            CorsairLedId.D_C3_146,
            CorsairLedId.D_C3_147,
            CorsairLedId.D_C3_148,
            CorsairLedId.D_C3_149,
            CorsairLedId.D_C3_150,
            #endregion
            #region RAM
            CorsairLedId.DRAM_1,
            CorsairLedId.DRAM_2,
            CorsairLedId.DRAM_3,
            CorsairLedId.DRAM_4,
            CorsairLedId.DRAM_5,
            CorsairLedId.DRAM_6,
            CorsairLedId.DRAM_7,
            CorsairLedId.DRAM_8,
            CorsairLedId.DRAM_9,
            CorsairLedId.DRAM_10,
            CorsairLedId.DRAM_12,
            #endregion
            #region Liquid Cooler
            CorsairLedId.LC_C1_1,
            CorsairLedId.LC_C1_2,
            CorsairLedId.LC_C1_3,
            CorsairLedId.LC_C1_4,
            CorsairLedId.LC_C1_5,
            CorsairLedId.LC_C1_6,
            CorsairLedId.LC_C1_7,
            CorsairLedId.LC_C1_8,
            CorsairLedId.LC_C1_9,
            CorsairLedId.LC_C1_10,
            CorsairLedId.LC_C1_11,
            CorsairLedId.LC_C1_12,
            CorsairLedId.LC_C1_13,
            CorsairLedId.LC_C1_14,
            CorsairLedId.LC_C1_15,
            CorsairLedId.LC_C1_16,
            CorsairLedId.LC_C1_17,
            CorsairLedId.LC_C1_18,
            CorsairLedId.LC_C1_19,
            CorsairLedId.LC_C1_20,
            CorsairLedId.LC_C1_21,
            CorsairLedId.LC_C1_22,
            CorsairLedId.LC_C1_23,
            CorsairLedId.LC_C1_24,
            CorsairLedId.LC_C1_25,
            CorsairLedId.LC_C1_26,
            CorsairLedId.LC_C1_27,
            CorsairLedId.LC_C1_28,
            CorsairLedId.LC_C1_29,
            CorsairLedId.LC_C1_30,
            CorsairLedId.LC_C1_31,
            CorsairLedId.LC_C1_32,
            CorsairLedId.LC_C1_33,
            CorsairLedId.LC_C1_34,
            CorsairLedId.LC_C1_35,
            CorsairLedId.LC_C1_36,
            CorsairLedId.LC_C1_37,
            CorsairLedId.LC_C1_38,
            CorsairLedId.LC_C1_39,
            CorsairLedId.LC_C1_40,
            CorsairLedId.LC_C1_41,
            CorsairLedId.LC_C1_42,
            CorsairLedId.LC_C1_43,
            CorsairLedId.LC_C1_44,
            CorsairLedId.LC_C1_45,
            CorsairLedId.LC_C1_46,
            CorsairLedId.LC_C1_47,
            CorsairLedId.LC_C1_48,
            CorsairLedId.LC_C1_49,
            CorsairLedId.LC_C1_50,
            CorsairLedId.LC_C1_51,
            CorsairLedId.LC_C1_52,
            CorsairLedId.LC_C1_53,
            CorsairLedId.LC_C1_54,
            CorsairLedId.LC_C1_55,
            CorsairLedId.LC_C1_56,
            CorsairLedId.LC_C1_57,
            CorsairLedId.LC_C1_58,
            CorsairLedId.LC_C1_59,
            CorsairLedId.LC_C1_60,
            CorsairLedId.LC_C1_61,
            CorsairLedId.LC_C1_62,
            CorsairLedId.LC_C1_63,
            CorsairLedId.LC_C1_64,
            CorsairLedId.LC_C1_65,
            CorsairLedId.LC_C1_66,
            CorsairLedId.LC_C1_67,
            CorsairLedId.LC_C1_68,
            CorsairLedId.LC_C1_69,
            CorsairLedId.LC_C1_70,
            CorsairLedId.LC_C1_71,
            CorsairLedId.LC_C1_72,
            CorsairLedId.LC_C1_73,
            CorsairLedId.LC_C1_74,
            CorsairLedId.LC_C1_75,
            CorsairLedId.LC_C1_76,
            CorsairLedId.LC_C1_77,
            CorsairLedId.LC_C1_78,
            CorsairLedId.LC_C1_79,
            CorsairLedId.LC_C1_80,
            CorsairLedId.LC_C1_81,
            CorsairLedId.LC_C1_82,
            CorsairLedId.LC_C1_83,
            CorsairLedId.LC_C1_84,
            CorsairLedId.LC_C1_85,
            CorsairLedId.LC_C1_86,
            CorsairLedId.LC_C1_87,
            CorsairLedId.LC_C1_88,
            CorsairLedId.LC_C1_89,
            CorsairLedId.LC_C1_90,
            CorsairLedId.LC_C1_91,
            CorsairLedId.LC_C1_92,
            CorsairLedId.LC_C1_93,
            CorsairLedId.LC_C1_94,
            CorsairLedId.LC_C1_95,
            CorsairLedId.LC_C1_96,
            CorsairLedId.LC_C1_97,
            CorsairLedId.LC_C1_98,
            CorsairLedId.LC_C1_99,
            CorsairLedId.LC_C1_100,
            CorsairLedId.LC_C1_101,
            CorsairLedId.LC_C1_102,
            CorsairLedId.LC_C1_103,
            CorsairLedId.LC_C1_104,
            CorsairLedId.LC_C1_105,
            CorsairLedId.LC_C1_106,
            CorsairLedId.LC_C1_107,
            CorsairLedId.LC_C1_108,
            CorsairLedId.LC_C1_109,
            CorsairLedId.LC_C1_110,
            CorsairLedId.LC_C1_111,
            CorsairLedId.LC_C1_112,
            CorsairLedId.LC_C1_113,
            CorsairLedId.LC_C1_114,
            CorsairLedId.LC_C1_115,
            CorsairLedId.LC_C1_116,
            CorsairLedId.LC_C1_117,
            CorsairLedId.LC_C1_118,
            CorsairLedId.LC_C1_119,
            CorsairLedId.LC_C1_120,
            CorsairLedId.LC_C1_121,
            CorsairLedId.LC_C1_122,
            CorsairLedId.LC_C1_123,
            CorsairLedId.LC_C1_124,
            CorsairLedId.LC_C1_125,
            CorsairLedId.LC_C1_126,
            CorsairLedId.LC_C1_127,
            CorsairLedId.LC_C1_128,
            CorsairLedId.LC_C1_129,
            CorsairLedId.LC_C1_130,
            CorsairLedId.LC_C1_131,
            CorsairLedId.LC_C1_132,
            CorsairLedId.LC_C1_133,
            CorsairLedId.LC_C1_134,
            CorsairLedId.LC_C1_135,
            CorsairLedId.LC_C1_136,
            CorsairLedId.LC_C1_137,
            CorsairLedId.LC_C1_138,
            CorsairLedId.LC_C1_139,
            CorsairLedId.LC_C1_140,
            CorsairLedId.LC_C1_141,
            CorsairLedId.LC_C1_142,
            CorsairLedId.LC_C1_143,
            CorsairLedId.LC_C1_144,
            CorsairLedId.LC_C1_145,
            CorsairLedId.LC_C1_146,
            CorsairLedId.LC_C1_147,
            CorsairLedId.LC_C1_148,
            CorsairLedId.LC_C1_149,
            CorsairLedId.LC_C1_150,
            #endregion
        };

        internal static readonly List<CorsairLedId> Channel1LedIds = EnumUtils.GetEnumValues<CorsairLedId>()
            .Where(id => Enum.GetName(typeof(CorsairLedId), id).StartsWith("D_C1_"))
            .ToList();

        internal static readonly List<CorsairLedId> Channel2LedIds = EnumUtils.GetEnumValues<CorsairLedId>()
            .Where(id => Enum.GetName(typeof(CorsairLedId), id).StartsWith("D_C2_"))
            .ToList();

        internal static readonly List<CorsairLedId> Channel3LedIds = EnumUtils.GetEnumValues<CorsairLedId>()
            .Where(id => Enum.GetName(typeof(CorsairLedId), id).StartsWith("D_C3_"))
            .ToList();

        internal static readonly List<List<CorsairLedId>> ChannelLeds = new List<List<CorsairLedId>> 
        {
            Channel1LedIds,
            Channel2LedIds,
            Channel3LedIds
        };

        public static string ToString(this CorsairLedColor corsairLedColor) => $"{corsairLedColor.LedId}, ({corsairLedColor.R},{corsairLedColor.G},{corsairLedColor.B})";

    }
}
